import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useTranslation} from 'react-i18next';
// import Axios from 'axios';
import Navbar from '../components/smart/Navbar/navbar'
import Homepage from '../components/smart/Homepage/homepage';
import { useSelector } from 'react-redux'

export default function Home() {
  const { t } = useTranslation();
  const state = useSelector((state) => state.state)


  // const click = () => {
  //   // console.log(process.env.BASE_URL) 
  //   Axios.get(process.env.BASE_URL+`/categories`)
  //     .then(res => {
  //       // setMyCategories(res.data);
  //       console.log(res.data)
  //       // console.log(res.data[1]['under_categories'][0].id)
  //     })
  //     .catch((error) => console.log(error.message));
  // }

  return (
    <div className={state.theme == 'light' ? 'theme-light' : 'theme-dark'}>
      <div className={styles.container}>
      <div className='app'>
      </div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>

        <Homepage/>

      </div>  
    </div>
  )
}
